/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractShowdownGrammarScopeProvider extends DelegatingScopeProvider {
}
