/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ShowdownGrammarStandaloneSetup extends ShowdownGrammarStandaloneSetupGenerated {

	public static void doSetup() {
		new ShowdownGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
