/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.github.niccomlt.showdown.ShowdownGrammarRuntimeModule;
import io.github.niccomlt.showdown.ShowdownGrammarStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ShowdownGrammarIdeSetup extends ShowdownGrammarStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ShowdownGrammarRuntimeModule(), new ShowdownGrammarIdeModule()));
	}
	
}
