/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.ide;


/**
 * Use this class to register ide components.
 */
public class ShowdownGrammarIdeModule extends AbstractShowdownGrammarIdeModule {
}
