/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ShowdownGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("io/github/niccomlt/showdown/parser/antlr/internal/InternalShowdownGrammar.tokens");
	}
}
