/**
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.showdownGrammar;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pokemon</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getNick <em>Nick</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getSpecie <em>Specie</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getItem <em>Item</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getAbility <em>Ability</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getLevel <em>Level</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getShiny <em>Shiny</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getHappiness <em>Happiness</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getEvs <em>Evs</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getNature <em>Nature</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getIvs <em>Ivs</em>}</li>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getMoves <em>Moves</em>}</li>
 * </ul>
 *
 * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon()
 * @model
 * @generated
 */
public interface Pokemon extends EObject
{
  /**
   * Returns the value of the '<em><b>Nick</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nick</em>' attribute.
   * @see #setNick(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Nick()
   * @model
   * @generated
   */
  String getNick();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getNick <em>Nick</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nick</em>' attribute.
   * @see #getNick()
   * @generated
   */
  void setNick(String value);

  /**
   * Returns the value of the '<em><b>Specie</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specie</em>' attribute.
   * @see #setSpecie(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Specie()
   * @model
   * @generated
   */
  String getSpecie();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getSpecie <em>Specie</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Specie</em>' attribute.
   * @see #getSpecie()
   * @generated
   */
  void setSpecie(String value);

  /**
   * Returns the value of the '<em><b>Item</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' attribute.
   * @see #setItem(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Item()
   * @model
   * @generated
   */
  String getItem();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getItem <em>Item</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item</em>' attribute.
   * @see #getItem()
   * @generated
   */
  void setItem(String value);

  /**
   * Returns the value of the '<em><b>Ability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ability</em>' attribute.
   * @see #setAbility(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Ability()
   * @model
   * @generated
   */
  String getAbility();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getAbility <em>Ability</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ability</em>' attribute.
   * @see #getAbility()
   * @generated
   */
  void setAbility(String value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see #setLevel(int)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Level()
   * @model
   * @generated
   */
  int getLevel();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see #getLevel()
   * @generated
   */
  void setLevel(int value);

  /**
   * Returns the value of the '<em><b>Shiny</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shiny</em>' attribute.
   * @see #setShiny(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Shiny()
   * @model
   * @generated
   */
  String getShiny();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getShiny <em>Shiny</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shiny</em>' attribute.
   * @see #getShiny()
   * @generated
   */
  void setShiny(String value);

  /**
   * Returns the value of the '<em><b>Happiness</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Happiness</em>' attribute.
   * @see #setHappiness(int)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Happiness()
   * @model
   * @generated
   */
  int getHappiness();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getHappiness <em>Happiness</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Happiness</em>' attribute.
   * @see #getHappiness()
   * @generated
   */
  void setHappiness(int value);

  /**
   * Returns the value of the '<em><b>Evs</b></em>' containment reference list.
   * The list contents are of type {@link io.github.niccomlt.showdown.showdownGrammar.Stat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evs</em>' containment reference list.
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Evs()
   * @model containment="true"
   * @generated
   */
  EList<Stat> getEvs();

  /**
   * Returns the value of the '<em><b>Nature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nature</em>' attribute.
   * @see #setNature(String)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Nature()
   * @model
   * @generated
   */
  String getNature();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Pokemon#getNature <em>Nature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nature</em>' attribute.
   * @see #getNature()
   * @generated
   */
  void setNature(String value);

  /**
   * Returns the value of the '<em><b>Ivs</b></em>' containment reference list.
   * The list contents are of type {@link io.github.niccomlt.showdown.showdownGrammar.Stat}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ivs</em>' containment reference list.
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Ivs()
   * @model containment="true"
   * @generated
   */
  EList<Stat> getIvs();

  /**
   * Returns the value of the '<em><b>Moves</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Moves</em>' attribute list.
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getPokemon_Moves()
   * @model unique="false"
   * @generated
   */
  EList<String> getMoves();

} // Pokemon
