/**
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.showdownGrammar;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Stat#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getStat()
 * @model
 * @generated
 */
public interface Stat extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getStat_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link io.github.niccomlt.showdown.showdownGrammar.Stat#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // Stat
