/**
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.showdownGrammar;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Team</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.niccomlt.showdown.showdownGrammar.Team#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getTeam()
 * @model
 * @generated
 */
public interface Team extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link io.github.niccomlt.showdown.showdownGrammar.Pokemon}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage#getTeam_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Pokemon> getElements();

} // Team
