/*
 * generated by Xtext 2.21.0
 */
package io.github.niccomlt.showdown.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractShowdownGrammarValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(io.github.niccomlt.showdown.showdownGrammar.ShowdownGrammarPackage.eINSTANCE);
		return result;
	}
}
